# secret.yaml - Stores Docker registry credentials as a Kubernetes Secret
#
# This manifest creates a Secret of type 'kubernetes.io/dockerconfigjson' in the 'automationsaan' namespace.
# The secret contains the base64-encoded Docker config, allowing Kubernetes to authenticate and pull images
# from a private registry (e.g., JFrog Artifactory) when deploying workloads. This is referenced by imagePullSecrets
# in your deployment manifests for secure, automated image pulls.

apiVersion: v1
kind: Secret
metadata:
  name: jfrog-artifact-cred
  namespace: automationsaan
data:
  .dockerconfigjson: **secret key goes here** # Replace with your base64-encoded Docker config JSON
type: kubernetes.io/dockerconfigjson